---
title: "Kawhi prediction"
author: "Jun Yu Chen"
date: "10/8/2022"
output:
  pdf_document: default
  html_document: default
---

```{r}

library(dplyr)
library(ggplot2)

##Filter NBA seasons after the year 2005
raw_nba_set<-read.csv("PER.csv")
new_nba_set<-raw_nba_set%>%filter(Year>="2005")%>%select(Year,Player,Pos,G,MP,PER) 


##Naming the raw injury dataset
raw_injury_set<-read.csv("injuries_2010-2020.csv")

##Selecting players who had out of season injuries
OutSeason<-raw_injury_set%>%filter(grepl("out for season",Notes))
Years<-substr(OutSeason$Date,1,4)
OutSeason$Years<-as.integer(substr(OutSeason$Date,1,4))
OutSeason<-OutSeason[,-c(1,3)]


##Joining datasets together
Injured_joined<-new_nba_set%>%inner_join(OutSeason,by=c("Player"="Relinquished","Year"="Years"))%>%distinct(Player,.keep_all= TRUE)
head(Injured_joined)



```


```{r cleaning stage 2}

library(showtext)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(grid)

##import cleaned data
injury_data_cleaned<-read.csv("injury_data_cleaned.csv")
injury_data_cleaned<-injury_data_cleaned%>%mutate(Avg_EFF_diff=After_EFF-Prev_EFF)

##EFF difference
EFF_difference<-injury_data_cleaned%>%ggplot(aes(x=Avg_EFF_diff,y=..density..))+
  geom_histogram(binwidth=.5, colour="black", fill="lightblue") +
  geom_vline(aes(xintercept=mean(Avg_EFF_diff, na.rm=TRUE)),  
               color="darkblue", linetype="dashed", size=1)+
  geom_density(color = "pink",size=1)+
  xlab("Individual Player Efficiency(EFF) difference ") +
  ggtitle("Individual Player Efficiency(EFF) Difference for Injured NBA Players ")+
  theme(plot.title = element_text(hjust = 0.5))+theme(panel.grid.major = element_blank(), panel.grid.minor =   element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"))



#EFF difference by Age groups

Age_18_25<-injury_data_cleaned%>%filter(Age>=18&Age<=25)%>%ggplot(aes(x=Avg_EFF_diff,y=..density..))+
  geom_histogram(binwidth=.5, colour="black", fill="lightblue")+
  geom_vline(aes(xintercept=mean(Avg_EFF_diff, na.rm=TRUE)),  color="#E69F00", linetype="dashed", size=1)+
  geom_density(color = "#0072B2" ,size=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor =   element_blank(),panel.background =        element_blank(), axis.line = element_line(colour = "black"))+
  xlab("Individual Player Efficiency(EFF) difference ") +
  ggtitle("Age Group 20-25 ")+
  theme(plot.title = element_text(hjust = 0.5))

Age_25_30<-injury_data_cleaned%>%filter(Age>25&Age<=30)%>%ggplot(aes(x=Avg_EFF_diff,y=..density..))+
  geom_histogram(binwidth=.5, colour="black", fill="lightblue")+
  geom_vline(aes(xintercept=mean(Avg_EFF_diff, na.rm=TRUE)),  color="#E69F00", linetype="dashed", size=1)+
  geom_density(color = "#0072B2" ,size=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor =   element_blank(),panel.background =        element_blank(), axis.line = element_line(colour = "black"))+
  xlab("Individual Player Efficiency(EFF) difference ") +
  ggtitle("Age Group 25-30 ")+
  theme(plot.title = element_text(hjust = 0.5))

Age_30_35<-injury_data_cleaned%>%filter(Age>30&Age<=35)%>%ggplot(aes(x=Avg_EFF_diff,y=..density..))+
  geom_histogram(binwidth=.5, colour="black", fill="lightblue")+
  geom_vline(aes(xintercept=mean(Avg_EFF_diff, na.rm=TRUE)),  color="#E69F00", linetype="dashed", size=1)+
  geom_density(color = "#0072B2" ,size=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor =   element_blank(),panel.background =        element_blank(), axis.line = element_line(colour = "black"))+
  xlab("Individual Player Efficiency(EFF) difference ") +
  ggtitle("Age Group 30-35 ")+
  theme(plot.title = element_text(hjust = 0.5))

Age_35_40<-injury_data_cleaned%>%filter(Age>35)%>%ggplot(aes(x=Avg_EFF_diff,y=..density..))+
  geom_histogram(binwidth=.5, colour="black", fill="lightblue")+
  geom_vline(aes(xintercept=mean(Avg_EFF_diff, na.rm=TRUE)),  color="#E69F00", linetype="dashed", size=1)+
  geom_density(color = "black" )+
  geom_density(color = "#0072B2" ,size=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor =element_blank(),panel.background =        element_blank(), axis.line = element_line(colour = "black"))+
  xlab("Individual Player Efficiency(EFF) difference ") +
  ggtitle("Age Group 35+ ")+
  theme(plot.title = element_text(hjust = 0.5))

grid.arrange(Age_18_25,Age_25_30,Age_30_35,Age_35_40,ncol=2,top = textGrob("EFF Difference for Injured NBA Players by Age Groups",gp=gpar(fontsize=15,font=1)))
plot


##Quartiles of Weight
with(injury_data_cleaned,summary(Weight))


#EFF difference by Position
injury_data_cleaned%>%filter(Pos==c("C","PF","SF","SG","PG"))%>%ggplot(aes(x=Avg_EFF_diff,y=..density..))+
  geom_histogram(binwidth=.5, colour="black", fill="lightblue")+
  geom_density(color = "pink",size=1)+
  geom_density(color = "burlywood3" ,size=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background =        element_blank(), axis.line = element_line(colour = "black"))+
  xlab("Individual Player Efficiency(EFF) difference ") +
  ggtitle("EFF Difference for Injured NBA Players by Positions")+
  theme(plot.title = element_text(hjust = 0.5))+
  facet_wrap(~Pos,scales='free',ncol=3)+
  scale_x_continuous(limits=c(-10,10)) + scale_y_continuous(limits=c(0,0.8))



```


```{r}
##EFF by Weight
Weight_77_93<-injury_data_cleaned%>%filter(Weight>76.66&Weight<=92.65)%>%ggplot(aes(x=Avg_EFF_diff,y=..density..))+
  geom_histogram(binwidth=.5, colour="black", fill="lightblue")+
  geom_vline(aes(xintercept=mean(Avg_EFF_diff, na.rm=TRUE)),  color="gray16", linetype="dashed", size=1)+
  geom_density(color = "burlywood3" ,size=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor =   element_blank(),panel.background =        element_blank(), axis.line = element_line(colour = "black"))+
  xlab("Efficiency Rating Difference(EFF_Diff)") +
  ggtitle("Weight Group 76-93 kg ")+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_density(color = "burlywood3",size=1 )+
  scale_x_continuous(limits=c(-20,15)) 

Weight_93_102<-injury_data_cleaned%>%filter(Weight>92.65&Weight<=102.06)%>%ggplot(aes(x=Avg_EFF_diff,y=..density..))+
  geom_histogram(binwidth=.5, colour="black", fill="lightblue")+
  geom_vline(aes(xintercept=mean(Avg_EFF_diff, na.rm=TRUE)),  color="gray16", linetype="dashed", size=1)+
  geom_density(color = "burlywood3" ,size=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor =   element_blank(),panel.background =        element_blank(), axis.line = element_line(colour = "black"))+
  xlab("Efficiency Rating Difference(EFF_Diff)") +
  ggtitle("Weight Group 93-102 kg ")+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_density(color = "burlywood3",size=1 )+
  scale_x_continuous(limits=c(-20,15))

Weight_102_109<-injury_data_cleaned%>%filter(Weight>102.06&Weight<=108.86)%>%ggplot(aes(x=Avg_EFF_diff,y=..density..))+
  geom_histogram(binwidth=.5, colour="black", fill="lightblue")+
  geom_vline(aes(xintercept=mean(Avg_EFF_diff, na.rm=TRUE)),  color="gray16", linetype="dashed", size=1)+
  geom_density(color = "burlywood3" ,size=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor =   element_blank(),panel.background =        element_blank(), axis.line = element_line(colour = "black"))+
  xlab("Efficiency Rating Difference(EFF_Diff)") +
  ggtitle("Weight Group 102-109 kg ")+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_density(color = "burlywood3",size=1 )+
  scale_x_continuous(limits=c(-20,15)) 


Weight_109_132<-injury_data_cleaned%>%filter(Weight>108.86&Weight<=131.09)%>%ggplot(aes(x=Avg_EFF_diff,y=..density..))+
  geom_histogram(binwidth=.5, colour="black", fill="lightblue")+
  geom_vline(aes(xintercept=mean(Avg_EFF_diff, na.rm=TRUE)),  color="gray16", linetype="dashed", size=1)+
  geom_density(color = "burlywood3" ,size=1)+
  theme(panel.grid.major = element_blank(), panel.grid.minor =   element_blank(),panel.background =        element_blank(), axis.line = element_line(colour = "black"))+
  xlab("Efficiency Rating Difference(EFF_Diff)") +
  ggtitle("Weight Group 109-132 kg ")+
  theme(plot.title = element_text(hjust = 0.5))+
  geom_density(color = "burlywood3",size=1 )+
  scale_x_continuous(limits=c(-20,15)) 

grid.arrange(Weight_77_93,Weight_93_102,Weight_102_109,Weight_109_132,ncol=2,top = textGrob("Efficiency Rating Difference (EFF_Diff) by Weight Groups",gp=gpar(fontsize=15,font=1)))
 
```


